logging:
  level:
    cn.gmwenterprise.website.dao: DEBUG

server:
  port: 4200

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://120.79.155.125:3306/my_website?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  redis:
    port: 6379
    url: localhost
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/

mybatis:
  type-aliases-package: cn.gmwenterprise.website.domain
  mapper-locations: classpath:dao-mapping/**
  config-location: classpath:mybatis.config.xml
