spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/permission?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.cqut.permission.domain

logging:
  level:
    cn.edu.cqut.permission.dao: DEBUG

