spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0 # 文件大于阈值则写入磁盘，否则存入内存
      location: E:/uploadFiles/file-upload-example
      max-file-size: 10MB
      max-request-size: 200MB
      resolve-lazily: true # 需要用到文件时才解析，请求能及时进入到controller

server:
  port: 8341
  servlet:
    context-path: /file-system
